var salarioDeLarissa = 2000
var salarioDeMaria = 5000
var salarioDeJonas = 1000
var salarioDeFrancisco = 3000
var reajuste = 10

var calculoDoReajusteDoSalario1 = salarioDeLarissa * reajuste / 100
var calculoDoReajusteDoSalario2 = salarioDeMaria * reajuste / 100
var calculoDoReajusteDoSalario3 = salarioDeJonas * reajuste / 100
var calculoDoReajusteDoSalario4 = salarioDeFrancisco * reajuste / 100
console.log ("O reajuste do salario de Larrisa eh:", calculoDoReajusteDoSalario1 + salarioDeLarissa)
console.log ("O reajuste do salario de Maria eh:", calculoDoReajusteDoSalario2 + salarioDeMaria)
console.log ("O reajuste do salario de Jonas eh:", calculoDoReajusteDoSalario3 + salarioDeJonas)
console.log ("O reajuste do salario de Francisco eh:", calculoDoReajusteDoSalario4 + salarioDeFrancisco)
